'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17626
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class JFLibraryErrors
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("JertiFramework.JFLibraryErrors", GetType(JFLibraryErrors).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El valor ingresado en el campo &quot;{0}&quot; no es válido. Solo se permiten años mayores al 2000.
        '''</summary>
        Public Shared ReadOnly Property Error_Año() As String
            Get
                Return ResourceManager.GetString("Error_Año", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Debe digitar la misma contraseña que ha escrito en el campo de “Nueva Contraseña”.
        '''</summary>
        Public Shared ReadOnly Property Error_Compare_New_PWD() As String
            Get
                Return ResourceManager.GetString("Error_Compare_New_PWD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El valor del campo &quot;DUI&quot; no es válido..
        '''</summary>
        Public Shared ReadOnly Property Error_DUI() As String
            Get
                Return ResourceManager.GetString("Error_DUI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El correo electrónico ingresado no es válido..
        '''</summary>
        Public Shared ReadOnly Property Error_EMail() As String
            Get
                Return ResourceManager.GetString("Error_EMail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La fecha debe ser escrita en formato &apos;dd/mm/aaaa&apos;..
        '''</summary>
        Public Shared ReadOnly Property Error_Fechas_DataType() As String
            Get
                Return ResourceManager.GetString("Error_Fechas_DataType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El campo &quot;{0}&quot; es obligatorio..
        '''</summary>
        Public Shared ReadOnly Property Error_Field_Required() As String
            Get
                Return ResourceManager.GetString("Error_Field_Required", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La hora debe ser escrita en formato &apos;hh:mm a.m./p.m.&apos;.
        '''</summary>
        Public Shared ReadOnly Property Error_Format_Hora() As String
            Get
                Return ResourceManager.GetString("Error_Format_Hora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La longitud mínima de caracteres para una contraseña es de 6..
        '''</summary>
        Public Shared ReadOnly Property Error_Length_PWD() As String
            Get
                Return ResourceManager.GetString("Error_Length_PWD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La longitud mínima de caracteres es de 6 para un usuario..
        '''</summary>
        Public Shared ReadOnly Property Error_Length_User() As String
            Get
                Return ResourceManager.GetString("Error_Length_User", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Este campo solo admite números enteros..
        '''</summary>
        Public Shared ReadOnly Property Error_OnlyEnteros() As String
            Get
                Return ResourceManager.GetString("Error_OnlyEnteros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Este campo solo admite caracteres alfanuméricos..
        '''</summary>
        Public Shared ReadOnly Property Error_OnlyLetras_with_Space() As String
            Get
                Return ResourceManager.GetString("Error_OnlyLetras_with_Space", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El rango de válores permitidos es de 1 hasta 20..
        '''</summary>
        Public Shared ReadOnly Property Error_Range_MiembrosFam() As String
            Get
                Return ResourceManager.GetString("Error_Range_MiembrosFam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Según el Decreto Legislativo No. 450, (conocido como “Ley del Nombre de la Persona Natural”), establece que el apellido de la persona debe estar conformado por 2 apellidos..
        '''</summary>
        Public Shared ReadOnly Property Error_Required_TwoApellidos() As String
            Get
                Return ResourceManager.GetString("Error_Required_TwoApellidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El no. de teléfono ingresado no es válido..
        '''</summary>
        Public Shared ReadOnly Property Error_Telefono() As String
            Get
                Return ResourceManager.GetString("Error_Telefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ocurrió un error inesperado al intentar conectar con la base de datos del sistema..
        '''</summary>
        Public Shared ReadOnly Property Error_Try_Catch_Server() As String
            Get
                Return ResourceManager.GetString("Error_Try_Catch_Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El nombre de usuario solo puedes estar compuesto por caracteres de la A-Z..
        '''</summary>
        Public Shared ReadOnly Property Error_UserSystem() As String
            Get
                Return ResourceManager.GetString("Error_UserSystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El campo de género sólo permite los valores &quot;M&quot; o &quot;F&quot;..
        '''</summary>
        Public Shared ReadOnly Property Error_Values_Genero() As String
            Get
                Return ResourceManager.GetString("Error_Values_Genero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Debe seleccionar un valor, ya sea &quot;SI&quot; o &quot;NO&quot;..
        '''</summary>
        Public Shared ReadOnly Property Error_YesOrNo() As String
            Get
                Return ResourceManager.GetString("Error_YesOrNo", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
