//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILEGROUP
    {
        public FILEGROUP()
        {
            this.FILEGROUP_VERSIONS = new HashSet<FILEGROUP_VERSIONS>();
        }
    
        public int ID_FILEGROUP { get; set; }
        public string FILEGROUP_NAME { get; set; }
    
        public virtual ICollection<FILEGROUP_VERSIONS> FILEGROUP_VERSIONS { get; set; }
    }
}
