//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILEGROUP_VERSIONS
    {
        public int ID_FILEGROUP { get; set; }
        public string FILENAME { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO { get; set; }
        public string FILEGROUP_ETIQUETA { get; set; }
    
        public virtual FILEGROUP FILEGROUP { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
