//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_CONSULTAR_EVALUACIONES_ACTIVAS_MODEL
    {
        public int ID_SOLUCION_PENDIENTE { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMA_ACTUALIZACION { get; set; }
    }
}
