//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_CONSULTAR_TODOS_FINDINGS_MODEL
    {
        public int ID { get; set; }
        public string TIPO_NOCONFORMIDAD { get; set; }
        public string COMENTARIO { get; set; }
        public string NO_RELACION { get; set; }
        public string TIPO_CORRECION { get; set; }
        public string ACCION_CORRECTIVA_SUGERIDA { get; set; }
        public Nullable<System.DateTime> FECHA_LIMITE { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string ESTADO { get; set; }
    }
}
