//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_CONSULTAR_TAREA_ARCHIVOS_MODEL
    {
        public int ID_TAREA { get; set; }
        public string TITULO_ARCHIVO { get; set; }
        public string NOMBRE_ARCHIVO { get; set; }
        public Nullable<System.DateTime> FECHA_SUBIDA { get; set; }
        public string USER_SUBIDA { get; set; }
        public string NOMBRE_USUARIO { get; set; }
    }
}
