//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_CONSTRUIR_SELF_MODEL
    {
        public Nullable<int> ID_JERARQUIA { get; set; }
        public Nullable<int> ID_PREGUNTA { get; set; }
        public string ARBOL { get; set; }
        public string TIPO_PREGUNTA { get; set; }
        public string DESCRIPCION_JERARQUIA { get; set; }
        public string CLASIFICACION { get; set; }
        public Nullable<int> NIVEL { get; set; }
        public string COMENTARIO_PREGUNTA { get; set; }
        public string ADJUNTAR_DOCUMENTO { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public int ID_TP_MULTIPLE { get; set; }
        public string LINK_COMENTARIO { get; set; }
    }
}
