//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_CONSULTAR_TAREA_COMENTARIOS_BYID_MODEL
    {
        public Nullable<long> ORDEN { get; set; }
        public int ID_COMENTARIO { get; set; }
        public int ID_TAREA { get; set; }
        public string COMENTARIO { get; set; }
        public System.DateTime FECHA_COMENTARIO { get; set; }
        public string USER_COMENTARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
    }
}
