//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_CONSULTAR_REVISION_PREGUNTASYRESPUESTAS_MODEL
    {
        public Nullable<int> ID_PREGUNTA { get; set; }
        public string ORDEN_JERARQUIA { get; set; }
        public string PREGUNTA { get; set; }
        public string RESPUESTA { get; set; }
        public string DOCUMENTO { get; set; }
        public string RESULTADO { get; set; }
        public string TIPO_PREGUNTA { get; set; }
        public string NORMA_GIDEM { get; set; }
    }
}
