//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_CONSULTAR_POLITICAS_OBJETIVOS_VIGENTES_MODEL
    {
        public int ID_POLITICA { get; set; }
        public string TEXT_POLITICA { get; set; }
        public string DESC_POLITICA { get; set; }
        public int ID_OBJETIVO { get; set; }
        public string TEXT_OBJETIVO { get; set; }
        public string TEXT_OBJETIVO_ACOTADO { get; set; }
    }
}
