//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_CONSULTAR_VERSIONES_FILEGROUP_MODEL
    {
        public Nullable<long> NO_VERSION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO { get; set; }
        public string ETIQUETA { get; set; }
    }
}
