//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_GRID_TAREAS_MODEL
    {
        public int ID_TAREA { get; set; }
        public int ID_PROYECTO { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public string TITULO_TAREA { get; set; }
        public string USER_RESPONSABLE { get; set; }
        public string RESPONSABLE_EJECUCION { get; set; }
        public Nullable<System.DateTime> FECHA_FINALIZACION { get; set; }
        public decimal PROGRESO { get; set; }
    }
}
