//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_GET_VALORES_ORGANIZACION_MODEL
    {
        public int ID_VALOR { get; set; }
        public int ID_INFORMACION { get; set; }
        public string TEXT_VALOR { get; set; }
        public string DESC_VALOR { get; set; }
    }
}
