//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_GET_NORMA_ISO_MODEL
    {
        public string ARBOL { get; set; }
        public Nullable<int> ID_JERARQUIA { get; set; }
        public string DESCRIPCION_JERARQUIA { get; set; }
        public string ES_PREGUNTA { get; set; }
        public Nullable<int> NIVEL { get; set; }
    }
}
