//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_GET_EVALUACIONES_MODEL
    {
        public int revision { get; set; }
        public string comentario { get; set; }
        public string idUsuario { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string USER_EVALUACION { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechaRevision { get; set; }
    }
}
