//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_GRID_FILESGROUP_MODEL
    {
        public int ID_FILEGROUP { get; set; }
        public string FILEGROUP_NAME { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMA_VERSION { get; set; }
        public string ETIQUETA { get; set; }
        public Nullable<int> VERSIONES { get; set; }
    }
}
