//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_GET_RESPONSES_EVALUACIONTEMP_MODEL
    {
        public int ID_PREGUNTA { get; set; }
        public string RESPUESTA_SIMPLE { get; set; }
        public string TIPO_RESPUESTA { get; set; }
    }
}
