//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_GET_INFO_ORGANIZACION_MODEL
    {
        public int ID_INFORMACION { get; set; }
        public string NOMBRE_ORG { get; set; }
        public string ESLOGAN_ORG { get; set; }
        public string ALCANCE_ORG { get; set; }
        public string MISION_ORG { get; set; }
        public string VISION_ORG { get; set; }
        public System.DateTime FECHA_INFORMACION { get; set; }
        public string logo { get; set; }
    }
}
