//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDG_SICACI.Database
{
    using System;
    
    public partial class SP_TIMELINE_TAREAS_MODEL
    {
        public int ID_TAREA { get; set; }
        public string TITULO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHA_COMENTARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string USUARIO { get; set; }
        public string DATOS_ADICIONALES { get; set; }
    }
}
